version: 2
jobs:
  build:
    docker:
      - image: circleci/node:8.9.3
      - image: circleci/mongo:latest

    working_directory: ~/repo

    steps:
      - checkout

      - run:
          name: update-npm
          command: 'npm install npm@5.6.0'

      # Download and cache dependencies
      - restore_cache:
          key: dependency-cache-{{ checksum "package.json" }}          

      - run:
          name: install-npm-wee
          command: npm install

      - save_cache:
          paths:
            - node_modules
          key: dependency-cache-{{ checksum "package.json" }}

      - run:
          name: test
          command: npm test

      - run:
          name: code coverage
          command: npm run coverage



